name: example
description: >
  The QR.Flutter example app.
version: 2.0.0
homepage: https://github.com/lukef/qr.flutter
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/logo_yakka.png
