name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 1.1.2
author: Luke Freeman <freeman.luke@gmail.com>
homepage: https://github.com/lukef/qr.flutter

environment:
  sdk: ">=2.0.0-dev.61.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^1.0.0

flutter:
  uses-material-design: false