name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 5.0.0
homepage: https://github.com/theyakka/qr.flutter

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.16.5

flutter:
  uses-material-design: false
